name = "livestore-sync-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "development"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-sync"
database_id = "b1b938d0-dd9e-46eb-ab60-8f4eaa63b279" 